### ISSUE TITLE
Customization 

### ISSUE THREAD

**Issue by JusteenDev** [NezitX/better-ui#2]
this is good extension i love it, but the custom css on setting on it doesnt have much docs how to use it i cant find andy docs to change my ui using custom css, but still good ui ⭐⭐⭐⭐⭐

**Comment by NezitX** [comment]
hi, thanks for using our plugin.

docs will be added soon ( contributing are welcomed ).

custom css is for devs who know what to do with css and editting app ui.

For now, you can use [Eruda Acode](https://acode.app/plugin/sebastianjnuwu.acode.eruda) plugin for providing a erdua in the app and u can use it to see element and selectors and change what's u want ensure thats u know css already and erdua how it works.

sorry for late response.

**Comment by NezitX** [comment]
fixed in new version

**Comment by JusteenDev** [comment]
Hey bro may i ask how do you make this acode extentions ? i want to make my own to and i dont know how to start

**Comment by NezitX** [comment]
see:

[Official Docs](https://acode.app/plugin-docs)
[Community Docs](
https://acode-plugin-docs.vercel.app/docs/getting-started/create-plugin)

[Official plugin template](https://github.com/deadlyjack/acode-plugin)
[Community plugin template](https://github.com/bajrangCoder/acode-plugin-template)

**Comment by JusteenDev** [comment]
> see:
> 
> [Official Docs](https://acode.app/plugin-docs)
> [Community Docs](
> https://acode-plugin-docs.vercel.app/docs/getting-started/create-plugin)
> 
> [Official plugin template](https://github.com/deadlyjack/acode-plugin)
> [Community plugin template](https://github.com/bajrangCoder/acode-plugin-template)
